/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../../mock-server/MockServerPool";
import { IttybitClient } from "../../../src/Client";

describe("Signatures", () => {
    test("create", async () => {
        const server = mockServerPool.createServer();
        const client = new IttybitClient({ apiKey: "test", version: "test", environment: server.baseUrl });
        const rawRequestBody = { filename: "video.mp4", folder: "example", expiry: 1735689600, method: "put" };
        const rawResponseBody = {
            domain: "you.ittybit.net",
            filename: "video.mp4",
            folder: "example",
            expiry: 1735689600,
            method: "put",
            signature: "a1b2c3d4e5f6...",
            url: "https://you.ittybit.net/example/video.mp4?expiry=1735689600&method=put&signature=a1b2c3d4e5f6...",
        };
        server
            .mockEndpoint()
            .post("/signatures")
            .header("Accept-Version", "2025-08-20")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.apiDev.signatures.create({
            filename: "video.mp4",
            folder: "example",
            expiry: 1735689600,
            method: "put",
        });
        expect(response).toEqual({
            domain: "you.ittybit.net",
            filename: "video.mp4",
            folder: "example",
            expiry: 1735689600,
            method: "put",
            signature: "a1b2c3d4e5f6...",
            url: "https://you.ittybit.net/example/video.mp4?expiry=1735689600&method=put&signature=a1b2c3d4e5f6...",
        });
    });
});
