/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SignaturesCreateResponse {
    domain: string;
    filename: string;
    folder?: string;
    expiry: number;
    method: string;
    signature: string;
    url: string;
}
