/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         title: "My Video Example",
 *         alt: "An example video used to demonstrate the ittybit API",
 *         metadata: {
 *             "customKey2": "a different custom value"
 *         }
 *     }
 */
export interface MediaCreateRequest {
    title?: string;
    alt?: string;
    metadata?: Record<string, unknown>;
}
