/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../index.js";

export interface Automation {
    id: string;
    name?: string;
    description?: string;
    trigger: Automation.Trigger;
    workflow: Automation.Workflow.Item[];
    status: Automation.Status;
    created: string;
    updated: string;
}

export namespace Automation {
    export interface Trigger {
        kind: "event";
        event: "media.created";
    }

    export type Workflow = Workflow.Item[];

    export namespace Workflow {
        export type Item = Ittybit.WorkflowTaskStep | Ittybit.ConditionsTaskStep;
    }

    export type Status = "active" | "paused";
    export const Status = {
        Active: "active",
        Paused: "paused",
    } as const;
}
