/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ConditionsTaskStep {
    kind: "conditions";
    conditions: ConditionsTaskStep.Conditions.Item[];
    next?: ConditionsTaskStep.Next.Item[];
}

export namespace ConditionsTaskStep {
    export type Conditions = Conditions.Item[];

    export namespace Conditions {
        export interface Item {
            prop?: string;
            value?: string;
        }
    }

    export type Next = Next.Item[];

    export namespace Next {
        export interface Item {
            kind?: string;
            ref?: string;
        }
    }
}
