/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ConfirmationResponse {
    meta?: ConfirmationResponse.Meta;
    data?: ConfirmationResponse.Data;
    error?: ConfirmationResponse.Error_;
    links?: ConfirmationResponse.Links;
}

export namespace ConfirmationResponse {
    export interface Meta {
        request_id?: string;
        org_id?: string;
        project_id?: string;
        version?: string;
        type?: Meta.Type;
    }

    export namespace Meta {
        export type Type = "object" | "list";
        export const Type = {
            Object: "object",
            List: "list",
        } as const;
    }

    export interface Data {
        message?: string;
    }

    export interface Error_ {
        message?: string;
    }

    export interface Links {
        self?: string;
        parent?: string;
    }
}
