/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface FileListResponse {
    meta?: FileListResponse.Meta;
    data?: FileListResponse.Data.Item[];
    error?: FileListResponse.Error_;
    links?: FileListResponse.Links;
}

export namespace FileListResponse {
    export interface Meta {
        request_id?: string;
        org_id?: string;
        project_id?: string;
        version?: string;
        type?: Meta.Type;
        limit?: number;
        total?: number;
        page?: number;
        pages?: number;
    }

    export namespace Meta {
        export type Type = "object" | "list";
        export const Type = {
            Object: "object",
            List: "list",
        } as const;
    }

    export type Data = Data.Item[];

    export namespace Data {
        export interface Item {
            id: string;
            media_id: string;
            object: Item.Object_;
            kind: Item.Kind;
            type: string;
            codec?: string;
            container?: string;
            width?: number;
            height?: number;
            orientation?: string;
            rotation?: number;
            transparency?: boolean;
            animated?: boolean;
            frames?: number;
            duration?: number;
            fps?: number;
            filesize: number;
            bitrate?: number;
            language?: string;
            label?: string;
            ref?: string;
            folder?: string;
            filename?: string;
            url: string;
            placeholder?: string;
            background?: string;
            metadata?: Record<string, unknown>;
            original?: boolean;
            created_by?: string;
            created: string;
            updated: string;
            status: Item.Status;
        }

        export namespace Item {
            export type Object_ = "source" | "track" | "intelligence";
            export const Object_ = {
                Source: "source",
                Track: "track",
                Intelligence: "intelligence",
            } as const;
            export type Kind = "video" | "image" | "audio";
            export const Kind = {
                Video: "video",
                Image: "image",
                Audio: "audio",
            } as const;
            export type Status = "waiting" | "processing" | "ready" | "failed";
            export const Status = {
                Waiting: "waiting",
                Processing: "processing",
                Ready: "ready",
                Failed: "failed",
            } as const;
        }
    }

    export interface Error_ {
        message?: string;
    }

    export interface Links {
        self?: string;
        first?: string;
        next?: string;
        prev?: string;
        last?: string;
    }
}
