/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../index.js";

export interface FileResponse {
    meta?: Ittybit.Meta | undefined;
    data?: Ittybit.File_;
    error?: Ittybit.Error_;
    links?: Ittybit.Links;
}
