/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface LinksList {
    self?: string;
    first?: string;
    next?: string;
    prev?: string;
    last?: string;
}
