/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../index.js";

export interface MediaListResponse {
    meta?: Ittybit.MetaList;
    data?: Ittybit.Media[];
    error?: Ittybit.Error_;
    links?: Ittybit.LinksList;
}
