/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../index.js";

export interface Media {
    id: string;
    object: string;
    kind?: Media.Kind;
    title?: string;
    alt?: string;
    width?: number;
    height?: number;
    duration?: number;
    files: Ittybit.MediaSource[];
    urls: Record<string, unknown>;
    background?: string;
    metadata?: Record<string, unknown>;
    created: string;
    updated: string;
}

export namespace Media {
    export type Kind = "video" | "image" | "audio";
    export const Kind = {
        Video: "video",
        Image: "image",
        Audio: "audio",
    } as const;
}
