/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface MetaList {
    request_id?: string;
    org_id?: string;
    project_id?: string;
    version?: string;
    type?: MetaList.Type;
    limit?: number;
    total?: number;
    page?: number;
    pages?: number;
}

export namespace MetaList {
    export type Type = "object" | "list";
    export const Type = {
        Object: "object",
        List: "list",
    } as const;
}
