/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SignatureResponse {
    meta?: SignatureResponse.Meta;
    data?: SignatureResponse.Data;
    error?: SignatureResponse.Error_;
    links?: SignatureResponse.Links;
}

export namespace SignatureResponse {
    export interface Meta {
        request_id?: string;
        org_id?: string;
        project_id?: string;
        version?: string;
        type?: Meta.Type;
    }

    export namespace Meta {
        export type Type = "object" | "list";
        export const Type = {
            Object: "object",
            List: "list",
        } as const;
    }

    export interface Data {
        domain: string;
        filename: string;
        folder?: string;
        expiry: number;
        method: string;
        signature: string;
        url: string;
    }

    export interface Error_ {
        message?: string;
    }

    export interface Links {
        self?: string;
        parent?: string;
    }
}
