/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../index.js";

export interface TaskListResponse {
    meta?: Ittybit.MetaList;
    data?: Ittybit.Task[];
    error?: Ittybit.Error_;
    links?: Ittybit.LinksList;
}
