/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface WorkflowTaskStep {
    kind: WorkflowTaskStep.Kind;
    ref?: string;
    next?: WorkflowTaskStep.Next.Item[];
}

export namespace WorkflowTaskStep {
    export type Kind =
        | "video"
        | "image"
        | "audio"
        | "chapters"
        | "subtitles"
        | "thumbnails"
        | "nsfw"
        | "speech"
        | "description"
        | "outline"
        | "prompt"
        | "http";
    export const Kind = {
        Video: "video",
        Image: "image",
        Audio: "audio",
        Chapters: "chapters",
        Subtitles: "subtitles",
        Thumbnails: "thumbnails",
        Nsfw: "nsfw",
        Speech: "speech",
        Description: "description",
        Outline: "outline",
        Prompt: "prompt",
        Http: "http",
    } as const;
    export type Next = Next.Item[];

    export namespace Next {
        export interface Item {
            kind?: string;
            ref?: string;
        }
    }
}
