/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         name: "My Updated Automation",
 *         workflow: [{
 *                 kind: "nsfw"
 *             }, {
 *                 kind: "description"
 *             }, {
 *                 kind: "image",
 *                 ref: "big_thumbnail"
 *             }, {
 *                 kind: "video",
 *                 next: [{
 *                         kind: "subtitle",
 *                         ref: "subtitle"
 *                     }]
 *             }],
 *         status: "active"
 *     }
 */
export interface AutomationsUpdateRequest {
    name?: string;
    description?: string;
    trigger?: AutomationsUpdateRequest.Trigger;
    workflow?: AutomationsUpdateRequest.Workflow.Item[];
    status?: AutomationsUpdateRequest.Status;
}

export namespace AutomationsUpdateRequest {
    export interface Trigger {
        kind: "event";
        event: "media.created";
    }

    export type Workflow = Workflow.Item[];

    export namespace Workflow {
        export interface Item {
            kind: Item.Kind;
            ref?: string;
            next?: Item.Next.Item[];
        }

        export namespace Item {
            export type Kind =
                | "video"
                | "image"
                | "audio"
                | "chapters"
                | "subtitles"
                | "thumbnails"
                | "nsfw"
                | "speech"
                | "description"
                | "outline"
                | "prompt"
                | "http";
            export const Kind = {
                Video: "video",
                Image: "image",
                Audio: "audio",
                Chapters: "chapters",
                Subtitles: "subtitles",
                Thumbnails: "thumbnails",
                Nsfw: "nsfw",
                Speech: "speech",
                Description: "description",
                Outline: "outline",
                Prompt: "prompt",
                Http: "http",
            } as const;
            export type Next = Next.Item[];

            export namespace Next {
                export interface Item {
                    kind?: string;
                    ref?: string;
                }
            }
        }
    }

    export type Status = "active" | "paused";
    export const Status = {
        Active: "active",
        Paused: "paused",
    } as const;
}
