/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../../../../index.js";

/**
 * @example
 *     {
 *         name: "My Example Automation",
 *         description: "This workflow will run whenever new media is created.",
 *         trigger: {
 *             kind: "event",
 *             event: "media.created"
 *         },
 *         workflow: [{
 *                 kind: "description"
 *             }, {
 *                 kind: "image",
 *                 ref: "thumbnail"
 *             }, {
 *                 kind: "video",
 *                 next: [{
 *                         kind: "subtitles",
 *                         ref: "subtitles"
 *                     }]
 *             }],
 *         status: "active"
 *     }
 */
export interface AutomationsCreateRequest {
    name?: string;
    description?: string;
    trigger: AutomationsCreateRequest.Trigger;
    workflow: Ittybit.WorkflowTaskStep[];
    status?: AutomationsCreateRequest.Status;
}

export namespace AutomationsCreateRequest {
    export interface Trigger {
        kind: "event";
        event: "media.created";
    }

    export type Status = "active" | "paused";
    export const Status = {
        Active: "active",
        Paused: "paused",
    } as const;
}
