/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Ittybit from "../../../../index.js";

/**
 * @example
 *     {
 *         name: "My Updated Automation",
 *         workflow: [{
 *                 kind: "nsfw"
 *             }, {
 *                 kind: "description"
 *             }, {
 *                 kind: "image",
 *                 ref: "big_thumbnail"
 *             }, {
 *                 kind: "video",
 *                 next: [{
 *                         kind: "subtitle",
 *                         ref: "subtitle"
 *                     }]
 *             }],
 *         status: "active"
 *     }
 */
export interface AutomationsUpdateRequest {
    name?: string;
    description?: string;
    trigger?: AutomationsUpdateRequest.Trigger;
    workflow?: Ittybit.WorkflowTaskStep[];
    status?: AutomationsUpdateRequest.Status;
}

export namespace AutomationsUpdateRequest {
    export interface Trigger {
        kind: "event";
        event: "media.created";
    }

    export type Status = "active" | "paused";
    export const Status = {
        Active: "active",
        Paused: "paused",
    } as const;
}
