/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         folder: "updated/folder",
 *         filename: "new_filename.mp4",
 *         metadata: {
 *             "customKey2": "a different custom value"
 *         }
 *     }
 */
export interface FilesUpdateRequest {
    folder?: string;
    filename?: string;
    ref?: string;
    metadata?: Record<string, unknown>;
}
