/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool";
import { IttybitClient } from "../../src/Client";

describe("Files", () => {
    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new IttybitClient({
            token: "test",
            version: "test",
            apiKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            meta: {
                request_id: "req_abcdefghij1234567890",
                org_id: "org_abcdefgh1234",
                project_id: "prj_abcdefgh1234",
                version: "2025-01-01",
                type: "list",
                limit: 20,
                total: 100,
                page: 1,
                pages: 5,
            },
            data: [
                {
                    id: "file_abcdefgh1234",
                    media_id: "med_abcdefgh1234",
                    object: "source",
                    kind: "video",
                    type: "video/mp4",
                    codec: "codec",
                    container: "container",
                    width: 1920,
                    height: 1080,
                    orientation: "orientation",
                    rotation: 1.1,
                    transparency: true,
                    animated: true,
                    frames: 1,
                    duration: 123.45,
                    fps: 1.1,
                    filesize: 12345678,
                    bitrate: 1,
                    language: "language",
                    label: "label",
                    ref: "ref",
                    folder: "folder",
                    filename: "file_abcdefgh1234.mp4",
                    url: "https://you.ittybit.net/file_abcdefgh1234.mp4",
                    placeholder: "placeholder",
                    background: "background",
                    metadata: { customKey: "your custom value" },
                    original: true,
                    created_by: "created_by",
                    created: "2025-01-01T01:23:45Z",
                    updated: "2025-01-01T01:23:45Z",
                    status: "ready",
                },
                {
                    id: "id",
                    media_id: "media_id",
                    object: "source",
                    kind: "video",
                    type: "type",
                    codec: "codec",
                    container: "container",
                    width: 1,
                    height: 1,
                    orientation: "orientation",
                    rotation: 1.1,
                    transparency: true,
                    animated: true,
                    frames: 1,
                    duration: 1.1,
                    fps: 1.1,
                    filesize: 1,
                    bitrate: 1,
                    language: "language",
                    label: "label",
                    ref: "ref",
                    folder: "folder",
                    filename: "filename",
                    url: "url",
                    placeholder: "placeholder",
                    background: "background",
                    metadata: { key: "value" },
                    original: true,
                    created_by: "created_by",
                    created: "2024-01-15T09:30:00Z",
                    updated: "2024-01-15T09:30:00Z",
                    status: "waiting",
                },
            ],
            links: {
                self: "https://api.ittybit.com/files?page=1",
                first: "https://api.ittybit.com/files?page=1",
                next: "https://api.ittybit.com/files?page=2",
                last: "https://api.ittybit.com/files?page=5",
            },
        };
        server.mockEndpoint().get("/files").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.files.list();
        expect(response).toEqual({
            meta: {
                request_id: "req_abcdefghij1234567890",
                org_id: "org_abcdefgh1234",
                project_id: "prj_abcdefgh1234",
                version: "2025-01-01",
                type: "list",
                limit: 20,
                total: 100,
                page: 1,
                pages: 5,
            },
            data: [
                {
                    id: "file_abcdefgh1234",
                    media_id: "med_abcdefgh1234",
                    object: "source",
                    kind: "video",
                    type: "video/mp4",
                    codec: "codec",
                    container: "container",
                    width: 1920,
                    height: 1080,
                    orientation: "orientation",
                    rotation: 1.1,
                    transparency: true,
                    animated: true,
                    frames: 1,
                    duration: 123.45,
                    fps: 1.1,
                    filesize: 12345678,
                    bitrate: 1,
                    language: "language",
                    label: "label",
                    ref: "ref",
                    folder: "folder",
                    filename: "file_abcdefgh1234.mp4",
                    url: "https://you.ittybit.net/file_abcdefgh1234.mp4",
                    placeholder: "placeholder",
                    background: "background",
                    metadata: {
                        customKey: "your custom value",
                    },
                    original: true,
                    created_by: "created_by",
                    created: "2025-01-01T01:23:45Z",
                    updated: "2025-01-01T01:23:45Z",
                    status: "ready",
                },
                {
                    id: "id",
                    media_id: "media_id",
                    object: "source",
                    kind: "video",
                    type: "type",
                    codec: "codec",
                    container: "container",
                    width: 1,
                    height: 1,
                    orientation: "orientation",
                    rotation: 1.1,
                    transparency: true,
                    animated: true,
                    frames: 1,
                    duration: 1.1,
                    fps: 1.1,
                    filesize: 1,
                    bitrate: 1,
                    language: "language",
                    label: "label",
                    ref: "ref",
                    folder: "folder",
                    filename: "filename",
                    url: "url",
                    placeholder: "placeholder",
                    background: "background",
                    metadata: {
                        key: "value",
                    },
                    original: true,
                    created_by: "created_by",
                    created: "2024-01-15T09:30:00Z",
                    updated: "2024-01-15T09:30:00Z",
                    status: "waiting",
                },
            ],
            links: {
                self: "https://api.ittybit.com/files?page=1",
                first: "https://api.ittybit.com/files?page=1",
                next: "https://api.ittybit.com/files?page=2",
                last: "https://api.ittybit.com/files?page=5",
            },
        });
    });

    test("create", async () => {
        const server = mockServerPool.createServer();
        const client = new IttybitClient({
            token: "test",
            version: "test",
            apiKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            url: "https://ittyb.it/sample.mp4",
            folder: "ittybit/samples",
            filename: "video.mp4",
            metadata: { customKey: "your custom value" },
        };
        const rawResponseBody = {
            meta: {
                request_id: "req_abcdefghij1234567890",
                org_id: "org_abcdefgh1234",
                project_id: "prj_abcdefgh1234",
                version: "2025-01-01",
                type: "object",
            },
            data: {
                id: "file_abcdefgh1234",
                media_id: "med_abcdefgh1234",
                object: "source",
                kind: "video",
                type: "video/mp4",
                codec: "codec",
                container: "container",
                width: 1920,
                height: 1080,
                orientation: "orientation",
                rotation: 1.1,
                transparency: true,
                animated: true,
                frames: 1,
                duration: 123.45,
                fps: 1.1,
                filesize: 12345678,
                bitrate: 1,
                language: "language",
                label: "label",
                ref: "ref",
                folder: "ittybit/samples",
                filename: "video.mp4",
                url: "https://you.ittybit.net/ittybit/samples/video.mp4",
                placeholder: "placeholder",
                background: "background",
                metadata: { customKey: "your custom value" },
                original: true,
                created_by: "created_by",
                created: "2025-01-01T01:23:45Z",
                updated: "2025-01-01T01:23:45Z",
                status: "ready",
            },
            links: { self: "https://api.ittybit.com/files/file_abcdefgh1234", parent: "https://api.ittybit.com/files" },
        };
        server
            .mockEndpoint()
            .post("/files")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.files.create({
            url: "https://ittyb.it/sample.mp4",
            folder: "ittybit/samples",
            filename: "video.mp4",
            metadata: {
                customKey: "your custom value",
            },
        });
        expect(response).toEqual({
            meta: {
                request_id: "req_abcdefghij1234567890",
                org_id: "org_abcdefgh1234",
                project_id: "prj_abcdefgh1234",
                version: "2025-01-01",
                type: "object",
            },
            data: {
                id: "file_abcdefgh1234",
                media_id: "med_abcdefgh1234",
                object: "source",
                kind: "video",
                type: "video/mp4",
                codec: "codec",
                container: "container",
                width: 1920,
                height: 1080,
                orientation: "orientation",
                rotation: 1.1,
                transparency: true,
                animated: true,
                frames: 1,
                duration: 123.45,
                fps: 1.1,
                filesize: 12345678,
                bitrate: 1,
                language: "language",
                label: "label",
                ref: "ref",
                folder: "ittybit/samples",
                filename: "video.mp4",
                url: "https://you.ittybit.net/ittybit/samples/video.mp4",
                placeholder: "placeholder",
                background: "background",
                metadata: {
                    customKey: "your custom value",
                },
                original: true,
                created_by: "created_by",
                created: "2025-01-01T01:23:45Z",
                updated: "2025-01-01T01:23:45Z",
                status: "ready",
            },
            links: {
                self: "https://api.ittybit.com/files/file_abcdefgh1234",
                parent: "https://api.ittybit.com/files",
            },
        });
    });

    test("get", async () => {
        const server = mockServerPool.createServer();
        const client = new IttybitClient({
            token: "test",
            version: "test",
            apiKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            meta: {
                request_id: "req_abcdefghij1234567890",
                org_id: "org_abcdefgh1234",
                project_id: "prj_abcdefgh1234",
                version: "2025-01-01",
                type: "object",
            },
            data: {
                id: "file_abcdefgh1234",
                media_id: "med_abcdefgh1234",
                object: "source",
                kind: "video",
                type: "video/mp4",
                codec: "codec",
                container: "container",
                width: 1920,
                height: 1080,
                orientation: "orientation",
                rotation: 1.1,
                transparency: true,
                animated: true,
                frames: 1,
                duration: 123.45,
                fps: 1.1,
                filesize: 12345678,
                bitrate: 1,
                language: "language",
                label: "label",
                ref: "ref",
                folder: "folder",
                filename: "file_abcdefgh1234.mp4",
                url: "https://you.ittybit.net/file_abcdefgh1234.mp4",
                placeholder: "placeholder",
                background: "background",
                metadata: { customKey: "your custom value" },
                original: true,
                created_by: "created_by",
                created: "2025-01-01T01:23:45Z",
                updated: "2025-01-01T01:23:45Z",
                status: "ready",
            },
            links: { self: "https://api.ittybit.com/files/file_abcdefgh1234", parent: "https://api.ittybit.com/files" },
        };
        server
            .mockEndpoint()
            .get("/files/file_abcdefgh1234")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.files.get("file_abcdefgh1234");
        expect(response).toEqual({
            meta: {
                request_id: "req_abcdefghij1234567890",
                org_id: "org_abcdefgh1234",
                project_id: "prj_abcdefgh1234",
                version: "2025-01-01",
                type: "object",
            },
            data: {
                id: "file_abcdefgh1234",
                media_id: "med_abcdefgh1234",
                object: "source",
                kind: "video",
                type: "video/mp4",
                codec: "codec",
                container: "container",
                width: 1920,
                height: 1080,
                orientation: "orientation",
                rotation: 1.1,
                transparency: true,
                animated: true,
                frames: 1,
                duration: 123.45,
                fps: 1.1,
                filesize: 12345678,
                bitrate: 1,
                language: "language",
                label: "label",
                ref: "ref",
                folder: "folder",
                filename: "file_abcdefgh1234.mp4",
                url: "https://you.ittybit.net/file_abcdefgh1234.mp4",
                placeholder: "placeholder",
                background: "background",
                metadata: {
                    customKey: "your custom value",
                },
                original: true,
                created_by: "created_by",
                created: "2025-01-01T01:23:45Z",
                updated: "2025-01-01T01:23:45Z",
                status: "ready",
            },
            links: {
                self: "https://api.ittybit.com/files/file_abcdefgh1234",
                parent: "https://api.ittybit.com/files",
            },
        });
    });

    test("delete", async () => {
        const server = mockServerPool.createServer();
        const client = new IttybitClient({
            token: "test",
            version: "test",
            apiKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            meta: {
                request_id: "req_abcdefghij1234567890",
                org_id: "org_abcdefgh1234",
                project_id: "prj_abcdefgh1234",
                version: "2025-01-01",
                type: "object",
            },
            data: { message: "file_abcdefgh1234 deleted" },
            links: { self: "self", parent: "https://api.ittybit.com/files" },
        };
        server
            .mockEndpoint()
            .delete("/files/file_abcdefgh1234")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.files.delete("file_abcdefgh1234");
        expect(response).toEqual({
            meta: {
                request_id: "req_abcdefghij1234567890",
                org_id: "org_abcdefgh1234",
                project_id: "prj_abcdefgh1234",
                version: "2025-01-01",
                type: "object",
            },
            data: {
                message: "file_abcdefgh1234 deleted",
            },
            links: {
                self: "self",
                parent: "https://api.ittybit.com/files",
            },
        });
    });

    test("update", async () => {
        const server = mockServerPool.createServer();
        const client = new IttybitClient({
            token: "test",
            version: "test",
            apiKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            folder: "updated/folder",
            filename: "new_filename.mp4",
            metadata: { customKey2: "a different custom value" },
        };
        const rawResponseBody = {
            meta: {
                request_id: "req_abcdefghij1234567890",
                org_id: "org_abcdefgh1234",
                project_id: "prj_abcdefgh1234",
                version: "2025-01-01",
                type: "object",
            },
            data: {
                id: "file_abcdefgh1234",
                media_id: "med_abcdefgh1234",
                object: "source",
                kind: "video",
                type: "video/mp4",
                codec: "codec",
                container: "container",
                width: 1920,
                height: 1080,
                orientation: "orientation",
                rotation: 1.1,
                transparency: true,
                animated: true,
                frames: 1,
                duration: 123.45,
                fps: 1.1,
                filesize: 12345678,
                bitrate: 1,
                language: "language",
                label: "label",
                ref: "ref",
                folder: "updated/folder",
                filename: "new_filename.mp4",
                url: "https://you.ittybit.net/updated/folder/new_filename.mp4",
                placeholder: "placeholder",
                background: "background",
                metadata: { customKey2: "a different custom value" },
                original: true,
                created_by: "created_by",
                created: "2025-01-01T01:23:45Z",
                updated: "2025-01-02T01:23:45Z",
                status: "ready",
            },
            links: { self: "https://api.ittybit.com/files/file_abcdefgh1234", parent: "https://api.ittybit.com/files" },
        };
        server
            .mockEndpoint()
            .patch("/files/file_abcdefgh1234")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.files.update("file_abcdefgh1234", {
            folder: "updated/folder",
            filename: "new_filename.mp4",
            metadata: {
                customKey2: "a different custom value",
            },
        });
        expect(response).toEqual({
            meta: {
                request_id: "req_abcdefghij1234567890",
                org_id: "org_abcdefgh1234",
                project_id: "prj_abcdefgh1234",
                version: "2025-01-01",
                type: "object",
            },
            data: {
                id: "file_abcdefgh1234",
                media_id: "med_abcdefgh1234",
                object: "source",
                kind: "video",
                type: "video/mp4",
                codec: "codec",
                container: "container",
                width: 1920,
                height: 1080,
                orientation: "orientation",
                rotation: 1.1,
                transparency: true,
                animated: true,
                frames: 1,
                duration: 123.45,
                fps: 1.1,
                filesize: 12345678,
                bitrate: 1,
                language: "language",
                label: "label",
                ref: "ref",
                folder: "updated/folder",
                filename: "new_filename.mp4",
                url: "https://you.ittybit.net/updated/folder/new_filename.mp4",
                placeholder: "placeholder",
                background: "background",
                metadata: {
                    customKey2: "a different custom value",
                },
                original: true,
                created_by: "created_by",
                created: "2025-01-01T01:23:45Z",
                updated: "2025-01-02T01:23:45Z",
                status: "ready",
            },
            links: {
                self: "https://api.ittybit.com/files/file_abcdefgh1234",
                parent: "https://api.ittybit.com/files",
            },
        });
    });
});
