/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool";
import { IttybitClient } from "../../src/Client";

describe("Media", () => {
    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new IttybitClient({ token: "test", version: "test", environment: server.baseUrl });

        const rawResponseBody = {
            meta: {
                request_id: "req_abcdefghij1234567890",
                org_id: "org_abcdefgh1234",
                project_id: "prj_abcdefgh1234",
                version: "2025-01-01",
                type: "list",
                limit: 20,
                total: 100,
                page: 1,
                pages: 5,
            },
            data: [
                {
                    id: "med_abcdefgh1234",
                    object: "media",
                    kind: "video",
                    title: "My Video Example",
                    alt: "An example video used to demonstrate the ittybit API",
                    width: 1920,
                    height: 1080,
                    duration: 123.45,
                    files: [
                        {
                            id: "file_abcdefgh1234",
                            object: "source",
                            kind: "video",
                            type: "video/mp4",
                            width: 1920,
                            height: 1080,
                            duration: 123.45,
                            filesize: 12345678,
                            ref: "original",
                            folder: "example",
                            filename: "video.mp4",
                            url: "https://you.ittybit.net/example/video.mp4",
                            created: "2025-01-01T01:23:45Z",
                            updated: "2025-01-01T01:23:45Z",
                            status: "waiting",
                        },
                        {
                            id: "file_abcdefgh5678",
                            object: "source",
                            kind: "image",
                            type: "image/png",
                            width: 640,
                            height: 360,
                            filesize: 123456,
                            ref: "thumbnail",
                            folder: "example",
                            filename: "image.png",
                            url: "https://you.ittybit.net/example/image.png",
                            created: "2025-01-01T01:23:46Z",
                            updated: "2025-01-01T01:23:46Z",
                            status: "waiting",
                        },
                    ],
                    urls: {
                        original: "https://you.ittybit.net/example/video.mp4",
                        thumbnail: "https://you.ittybit.net/example/image.png",
                    },
                    background: "#2OBO75",
                    metadata: { customKey: "your custom value" },
                    created: "2025-01-01T01:23:45Z",
                    updated: "2025-01-01T01:23:46Z",
                },
                {
                    id: "id",
                    object: "object",
                    kind: "video",
                    title: "title",
                    alt: "alt",
                    width: 1,
                    height: 1,
                    duration: 1.1,
                    files: [
                        {
                            id: "id",
                            object: "source",
                            kind: "video",
                            type: "type",
                            filesize: 1,
                            url: "url",
                            created: "2024-01-15T09:30:00Z",
                            updated: "2024-01-15T09:30:00Z",
                            status: "waiting",
                        },
                    ],
                    urls: { key: "value" },
                    background: "background",
                    metadata: { key: "value" },
                    created: "2024-01-15T09:30:00Z",
                    updated: "2024-01-15T09:30:00Z",
                },
            ],
            links: {
                self: "https://api.ittybit.com/media?page=1",
                first: "https://api.ittybit.com/media?page=1",
                next: "https://api.ittybit.com/media?page=2",
                last: "https://api.ittybit.com/media?page=5",
            },
        };
        server.mockEndpoint().get("/media").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.media.list();
        expect(response).toEqual({
            meta: {
                request_id: "req_abcdefghij1234567890",
                org_id: "org_abcdefgh1234",
                project_id: "prj_abcdefgh1234",
                version: "2025-01-01",
                type: "list",
                limit: 20,
                total: 100,
                page: 1,
                pages: 5,
            },
            data: [
                {
                    id: "med_abcdefgh1234",
                    object: "media",
                    kind: "video",
                    title: "My Video Example",
                    alt: "An example video used to demonstrate the ittybit API",
                    width: 1920,
                    height: 1080,
                    duration: 123.45,
                    files: [
                        {
                            id: "file_abcdefgh1234",
                            object: "source",
                            kind: "video",
                            type: "video/mp4",
                            width: 1920,
                            height: 1080,
                            duration: 123.45,
                            filesize: 12345678,
                            ref: "original",
                            folder: "example",
                            filename: "video.mp4",
                            url: "https://you.ittybit.net/example/video.mp4",
                            created: "2025-01-01T01:23:45Z",
                            updated: "2025-01-01T01:23:45Z",
                            status: "waiting",
                        },
                        {
                            id: "file_abcdefgh5678",
                            object: "source",
                            kind: "image",
                            type: "image/png",
                            width: 640,
                            height: 360,
                            filesize: 123456,
                            ref: "thumbnail",
                            folder: "example",
                            filename: "image.png",
                            url: "https://you.ittybit.net/example/image.png",
                            created: "2025-01-01T01:23:46Z",
                            updated: "2025-01-01T01:23:46Z",
                            status: "waiting",
                        },
                    ],
                    urls: {
                        original: "https://you.ittybit.net/example/video.mp4",
                        thumbnail: "https://you.ittybit.net/example/image.png",
                    },
                    background: "#2OBO75",
                    metadata: {
                        customKey: "your custom value",
                    },
                    created: "2025-01-01T01:23:45Z",
                    updated: "2025-01-01T01:23:46Z",
                },
                {
                    id: "id",
                    object: "object",
                    kind: "video",
                    title: "title",
                    alt: "alt",
                    width: 1,
                    height: 1,
                    duration: 1.1,
                    files: [
                        {
                            id: "id",
                            object: "source",
                            kind: "video",
                            type: "type",
                            filesize: 1,
                            url: "url",
                            created: "2024-01-15T09:30:00Z",
                            updated: "2024-01-15T09:30:00Z",
                            status: "waiting",
                        },
                    ],
                    urls: {
                        key: "value",
                    },
                    background: "background",
                    metadata: {
                        key: "value",
                    },
                    created: "2024-01-15T09:30:00Z",
                    updated: "2024-01-15T09:30:00Z",
                },
            ],
            links: {
                self: "https://api.ittybit.com/media?page=1",
                first: "https://api.ittybit.com/media?page=1",
                next: "https://api.ittybit.com/media?page=2",
                last: "https://api.ittybit.com/media?page=5",
            },
        });
    });

    test("create", async () => {
        const server = mockServerPool.createServer();
        const client = new IttybitClient({ token: "test", version: "test", environment: server.baseUrl });
        const rawRequestBody = {
            title: "My Video Example",
            alt: "An example video used to demonstrate the ittybit API",
            metadata: { customKey2: "a different custom value" },
        };
        const rawResponseBody = {
            meta: {
                request_id: "req_abcdefghij1234567890",
                org_id: "org_abcdefgh1234",
                project_id: "prj_abcdefgh1234",
                version: "2025-01-01",
                type: "object",
            },
            data: {
                id: "med_abcdefgh1234",
                object: "media",
                title: "My Video Example",
                alt: "An example video used to demonstrate the ittybit API",
                width: 1,
                height: 1,
                duration: 1.1,
                files: [
                    {
                        id: "id",
                        object: "source",
                        kind: "video",
                        type: "type",
                        filesize: 1,
                        url: "url",
                        created: "2024-01-15T09:30:00Z",
                        updated: "2024-01-15T09:30:00Z",
                        status: "waiting",
                    },
                ],
                urls: { key: "value" },
                metadata: { customKey: "your custom value" },
                created: "2025-01-01T01:23:45Z",
                updated: "2025-01-01T01:23:45Z",
            },
            links: { self: "https://api.ittybit.com/media/med_abcdefgh1234", parent: "https://api.ittybit.com/media" },
        };
        server
            .mockEndpoint()
            .post("/media")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.media.create({
            title: "My Video Example",
            alt: "An example video used to demonstrate the ittybit API",
            metadata: {
                customKey2: "a different custom value",
            },
        });
        expect(response).toEqual({
            meta: {
                request_id: "req_abcdefghij1234567890",
                org_id: "org_abcdefgh1234",
                project_id: "prj_abcdefgh1234",
                version: "2025-01-01",
                type: "object",
            },
            data: {
                id: "med_abcdefgh1234",
                object: "media",
                title: "My Video Example",
                alt: "An example video used to demonstrate the ittybit API",
                width: 1,
                height: 1,
                duration: 1.1,
                files: [
                    {
                        id: "id",
                        object: "source",
                        kind: "video",
                        type: "type",
                        filesize: 1,
                        url: "url",
                        created: "2024-01-15T09:30:00Z",
                        updated: "2024-01-15T09:30:00Z",
                        status: "waiting",
                    },
                ],
                urls: {
                    key: "value",
                },
                metadata: {
                    customKey: "your custom value",
                },
                created: "2025-01-01T01:23:45Z",
                updated: "2025-01-01T01:23:45Z",
            },
            links: {
                self: "https://api.ittybit.com/media/med_abcdefgh1234",
                parent: "https://api.ittybit.com/media",
            },
        });
    });

    test("get", async () => {
        const server = mockServerPool.createServer();
        const client = new IttybitClient({ token: "test", version: "test", environment: server.baseUrl });

        const rawResponseBody = {
            meta: {
                request_id: "req_abcdefghij1234567890",
                org_id: "org_abcdefgh1234",
                project_id: "prj_abcdefgh1234",
                version: "2025-01-01",
                type: "object",
            },
            data: {
                id: "med_abcdefgh1234",
                object: "media",
                kind: "video",
                title: "My Video Example",
                alt: "An example video used to demonstrate the ittybit API",
                width: 1920,
                height: 1080,
                duration: 123.45,
                files: [
                    {
                        id: "file_abcdefgh1234",
                        object: "source",
                        kind: "video",
                        type: 'video/mp4; codecs="avc1.6431, mp4a.40.2"',
                        width: 1920,
                        height: 1080,
                        duration: 123.45,
                        filesize: 12345678,
                        ref: "original",
                        folder: "example",
                        filename: "video.mp4",
                        url: "https://you.ittybit.net/example/video.mp4",
                        created: "2025-01-01T01:23:45Z",
                        updated: "2025-01-01T01:23:45Z",
                        status: "waiting",
                    },
                    {
                        id: "file_abcdefgh5678",
                        object: "source",
                        kind: "image",
                        type: "image/png",
                        width: 640,
                        height: 360,
                        filesize: 123456,
                        ref: "thumbnail",
                        folder: "example",
                        filename: "image.png",
                        url: "https://you.ittybit.net/example/image.png",
                        created: "2025-01-01T01:23:46Z",
                        updated: "2025-01-01T01:23:46Z",
                        status: "waiting",
                    },
                ],
                urls: {
                    original: "https://you.ittybit.net/example/video.mp4",
                    thumbnail: "https://you.ittybit.net/example/image.png",
                },
                background: "#2OBO75",
                metadata: { customKey: "your custom value" },
                created: "2025-01-01T01:23:45Z",
                updated: "2025-01-01T01:23:46Z",
            },
            links: { self: "https://api.ittybit.com/media/med_abcdefgh1234", parent: "https://api.ittybit.com/media" },
        };
        server
            .mockEndpoint()
            .get("/media/med_abcdefgh1234")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.media.get("med_abcdefgh1234");
        expect(response).toEqual({
            meta: {
                request_id: "req_abcdefghij1234567890",
                org_id: "org_abcdefgh1234",
                project_id: "prj_abcdefgh1234",
                version: "2025-01-01",
                type: "object",
            },
            data: {
                id: "med_abcdefgh1234",
                object: "media",
                kind: "video",
                title: "My Video Example",
                alt: "An example video used to demonstrate the ittybit API",
                width: 1920,
                height: 1080,
                duration: 123.45,
                files: [
                    {
                        id: "file_abcdefgh1234",
                        object: "source",
                        kind: "video",
                        type: 'video/mp4; codecs="avc1.6431, mp4a.40.2"',
                        width: 1920,
                        height: 1080,
                        duration: 123.45,
                        filesize: 12345678,
                        ref: "original",
                        folder: "example",
                        filename: "video.mp4",
                        url: "https://you.ittybit.net/example/video.mp4",
                        created: "2025-01-01T01:23:45Z",
                        updated: "2025-01-01T01:23:45Z",
                        status: "waiting",
                    },
                    {
                        id: "file_abcdefgh5678",
                        object: "source",
                        kind: "image",
                        type: "image/png",
                        width: 640,
                        height: 360,
                        filesize: 123456,
                        ref: "thumbnail",
                        folder: "example",
                        filename: "image.png",
                        url: "https://you.ittybit.net/example/image.png",
                        created: "2025-01-01T01:23:46Z",
                        updated: "2025-01-01T01:23:46Z",
                        status: "waiting",
                    },
                ],
                urls: {
                    original: "https://you.ittybit.net/example/video.mp4",
                    thumbnail: "https://you.ittybit.net/example/image.png",
                },
                background: "#2OBO75",
                metadata: {
                    customKey: "your custom value",
                },
                created: "2025-01-01T01:23:45Z",
                updated: "2025-01-01T01:23:46Z",
            },
            links: {
                self: "https://api.ittybit.com/media/med_abcdefgh1234",
                parent: "https://api.ittybit.com/media",
            },
        });
    });

    test("delete", async () => {
        const server = mockServerPool.createServer();
        const client = new IttybitClient({ token: "test", version: "test", environment: server.baseUrl });

        const rawResponseBody = {
            meta: {
                request_id: "req_abcdefghij1234567890",
                org_id: "org_abcdefgh1234",
                project_id: "prj_abcdefgh1234",
                version: "2025-01-01",
                type: "object",
            },
            data: { message: "med_abcdefgh1234 deleted" },
            links: { self: "self", parent: "https://api.ittybit.com/media" },
        };
        server
            .mockEndpoint()
            .delete("/media/med_abcdefgh1234")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.media.delete("med_abcdefgh1234");
        expect(response).toEqual({
            meta: {
                request_id: "req_abcdefghij1234567890",
                org_id: "org_abcdefgh1234",
                project_id: "prj_abcdefgh1234",
                version: "2025-01-01",
                type: "object",
            },
            data: {
                message: "med_abcdefgh1234 deleted",
            },
            links: {
                self: "self",
                parent: "https://api.ittybit.com/media",
            },
        });
    });

    test("update", async () => {
        const server = mockServerPool.createServer();
        const client = new IttybitClient({ token: "test", version: "test", environment: server.baseUrl });
        const rawRequestBody = {
            title: "Updated Video Example",
            alt: "An updated example video used to demonstrate the ittybit API",
            metadata: { customKey2: "a different custom value" },
        };
        const rawResponseBody = {
            meta: {
                request_id: "req_abcdefghij1234567890",
                org_id: "org_abcdefgh1234",
                project_id: "prj_abcdefgh1234",
                version: "2025-01-01",
                type: "object",
            },
            data: {
                id: "med_abcdefgh1234",
                object: "media",
                kind: "video",
                title: "Updated Video Example",
                alt: "An updated example video used to demonstrate the ittybit API",
                width: 1920,
                height: 1080,
                duration: 123.45,
                files: [
                    {
                        id: "file_abcdefgh1234",
                        object: "source",
                        kind: "video",
                        type: "type",
                        filesize: 1,
                        url: "url",
                        created: "2024-01-15T09:30:00Z",
                        updated: "2024-01-15T09:30:00Z",
                        status: "waiting",
                    },
                    {
                        id: "file_abcdefgh5678",
                        object: "source",
                        kind: "video",
                        type: "type",
                        filesize: 1,
                        url: "url",
                        created: "2024-01-15T09:30:00Z",
                        updated: "2024-01-15T09:30:00Z",
                        status: "waiting",
                    },
                ],
                urls: {
                    original: "https://you.ittybit.net/example/video.mp4",
                    thumbnail: "https://you.ittybit.net/example/image.png",
                },
                background: "#2OBO75",
                metadata: { customKey: "your custom value" },
                created: "2025-01-01T01:23:45Z",
                updated: "2025-01-01T01:23:46Z",
            },
            links: { self: "https://api.ittybit.com/media/med_abcdefgh1234", parent: "https://api.ittybit.com/media" },
        };
        server
            .mockEndpoint()
            .patch("/media/med_abcdefgh1234")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.media.update("med_abcdefgh1234", {
            title: "Updated Video Example",
            alt: "An updated example video used to demonstrate the ittybit API",
            metadata: {
                customKey2: "a different custom value",
            },
        });
        expect(response).toEqual({
            meta: {
                request_id: "req_abcdefghij1234567890",
                org_id: "org_abcdefgh1234",
                project_id: "prj_abcdefgh1234",
                version: "2025-01-01",
                type: "object",
            },
            data: {
                id: "med_abcdefgh1234",
                object: "media",
                kind: "video",
                title: "Updated Video Example",
                alt: "An updated example video used to demonstrate the ittybit API",
                width: 1920,
                height: 1080,
                duration: 123.45,
                files: [
                    {
                        id: "file_abcdefgh1234",
                        object: "source",
                        kind: "video",
                        type: "type",
                        filesize: 1,
                        url: "url",
                        created: "2024-01-15T09:30:00Z",
                        updated: "2024-01-15T09:30:00Z",
                        status: "waiting",
                    },
                    {
                        id: "file_abcdefgh5678",
                        object: "source",
                        kind: "video",
                        type: "type",
                        filesize: 1,
                        url: "url",
                        created: "2024-01-15T09:30:00Z",
                        updated: "2024-01-15T09:30:00Z",
                        status: "waiting",
                    },
                ],
                urls: {
                    original: "https://you.ittybit.net/example/video.mp4",
                    thumbnail: "https://you.ittybit.net/example/image.png",
                },
                background: "#2OBO75",
                metadata: {
                    customKey: "your custom value",
                },
                created: "2025-01-01T01:23:45Z",
                updated: "2025-01-01T01:23:46Z",
            },
            links: {
                self: "https://api.ittybit.com/media/med_abcdefgh1234",
                parent: "https://api.ittybit.com/media",
            },
        });
    });
});
