/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool";
import { IttybitClient } from "../../src/Client";

describe("Signatures", () => {
    test("create", async () => {
        const server = mockServerPool.createServer();
        const client = new IttybitClient({ token: "test", version: "test", environment: server.baseUrl });
        const rawRequestBody = { filename: "video.mp4", folder: "example", expiry: 1735689600, method: "put" };
        const rawResponseBody = {
            meta: {
                request_id: "req_abcdefghij1234567890",
                org_id: "org_abcdefgh1234",
                project_id: "prj_abcdefgh1234",
                version: "2025-01-01",
                type: "object",
            },
            data: {
                domain: "you.ittybit.net",
                filename: "video.mp4",
                folder: "example",
                expiry: 1735689600,
                method: "put",
                signature: "a1b2c3d4e5f6...",
                url: "https://you.ittybit.net/example/video.mp4?expiry=1735689600&method=put&signature=a1b2c3d4e5f6...",
            },
            error: { message: "message" },
            links: { self: "self", parent: "/signatures" },
        };
        server
            .mockEndpoint()
            .post("/signatures")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.signatures.create({
            filename: "video.mp4",
            folder: "example",
            expiry: 1735689600,
            method: "put",
        });
        expect(response).toEqual({
            meta: {
                request_id: "req_abcdefghij1234567890",
                org_id: "org_abcdefgh1234",
                project_id: "prj_abcdefgh1234",
                version: "2025-01-01",
                type: "object",
            },
            data: {
                domain: "you.ittybit.net",
                filename: "video.mp4",
                folder: "example",
                expiry: 1735689600,
                method: "put",
                signature: "a1b2c3d4e5f6...",
                url: "https://you.ittybit.net/example/video.mp4?expiry=1735689600&method=put&signature=a1b2c3d4e5f6...",
            },
            error: {
                message: "message",
            },
            links: {
                self: "self",
                parent: "/signatures",
            },
        });
    });
});
