/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments.js";
import * as core from "./core/index.js";
import { mergeHeaders } from "./core/headers.js";
import { Automations } from "./api/resources/automations/client/Client.js";
import { Files } from "./api/resources/files/client/Client.js";
import { Media } from "./api/resources/media/client/Client.js";
import { Tasks } from "./api/resources/tasks/client/Client.js";
import { Signatures } from "./api/resources/signatures/client/Client.js";

export declare namespace IttybitClient {
    export interface Options {
        environment?: core.Supplier<environments.IttybitEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token: core.Supplier<core.BearerToken>;
        /** Override the ACCEPT_VERSION header */
        version?: core.Supplier<string | undefined>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
        fetcher?: core.FetchFunction;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Override the ACCEPT_VERSION header */
        version?: string | undefined;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }
}

export class IttybitClient {
    protected readonly _options: IttybitClient.Options;
    protected _automations: Automations | undefined;
    protected _files: Files | undefined;
    protected _media: Media | undefined;
    protected _tasks: Tasks | undefined;
    protected _signatures: Signatures | undefined;

    constructor(_options: IttybitClient.Options) {
        this._options = {
            ..._options,
            headers: mergeHeaders(
                {
                    ACCEPT_VERSION: _options?.version,
                    "X-Fern-Language": "JavaScript",
                    "X-Fern-SDK-Name": "@ittybit/sdk",
                    "X-Fern-SDK-Version": "0.8.7.1",
                    "User-Agent": "@ittybit/sdk/0.8.7.1",
                    "X-Fern-Runtime": core.RUNTIME.type,
                    "X-Fern-Runtime-Version": core.RUNTIME.version,
                },
                _options?.headers,
            ),
        };
    }

    public get automations(): Automations {
        return (this._automations ??= new Automations(this._options));
    }

    public get files(): Files {
        return (this._files ??= new Files(this._options));
    }

    public get media(): Media {
        return (this._media ??= new Media(this._options));
    }

    public get tasks(): Tasks {
        return (this._tasks ??= new Tasks(this._options));
    }

    public get signatures(): Signatures {
        return (this._signatures ??= new Signatures(this._options));
    }
}
