/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const IttybitEnvironment = {
    Default: "https://api.ittybit.com",
} as const;

export type IttybitEnvironment = typeof IttybitEnvironment.Default;
