/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AutomationResponse {
    id: string;
    name?: string;
    description?: string;
    trigger: AutomationResponse.Trigger;
    workflow: AutomationResponse.Workflow.Item[];
    status: AutomationResponse.Status;
    created: string;
    updated: string;
}

export namespace AutomationResponse {
    export interface Trigger {
        kind: "event";
        event: "media.created";
    }

    export type Workflow = Workflow.Item[];

    export namespace Workflow {
        export type Item =
            | {
                  kind:
                      | "video"
                      | "image"
                      | "audio"
                      | "chapters"
                      | "subtitles"
                      | "thumbnails"
                      | "nsfw"
                      | "speech"
                      | "description"
                      | "outline"
                      | "prompt"
                      | "http";
                  ref?: string | undefined;
                  next?:
                      | {
                            kind?: string | undefined;
                            ref?: string | undefined;
                        }[]
                      | undefined;
              }
            | {
                  kind: "conditions";
                  conditions: {
                      prop?: string | undefined;
                      value?: string | undefined;
                  }[];
                  next?:
                      | {
                            kind?: string | undefined;
                            ref?: string | undefined;
                        }[]
                      | undefined;
              };
    }

    export type Status = "active" | "paused";
    export const Status = {
        Active: "active",
        Paused: "paused",
    } as const;
}
