/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface FileListResponseItem {
    id: string;
    media_id: string;
    object: FileListResponseItem.Object_;
    kind: FileListResponseItem.Kind;
    type: string;
    codec?: string;
    container?: string;
    width?: number;
    height?: number;
    orientation?: string;
    rotation?: number;
    transparency?: boolean;
    animated?: boolean;
    frames?: number;
    duration?: number;
    fps?: number;
    filesize: number;
    bitrate?: number;
    language?: string;
    label?: string;
    ref?: string;
    folder?: string;
    filename?: string;
    url: string;
    placeholder?: string;
    background?: string;
    metadata?: Record<string, unknown>;
    original?: boolean;
    created_by?: string;
    created: string;
    updated: string;
    status: FileListResponseItem.Status;
}

export namespace FileListResponseItem {
    export type Object_ = "source" | "track" | "intelligence";
    export const Object_ = {
        Source: "source",
        Track: "track",
        Intelligence: "intelligence",
    } as const;
    export type Kind = "video" | "image" | "audio";
    export const Kind = {
        Video: "video",
        Image: "image",
        Audio: "audio",
    } as const;
    export type Status = "waiting" | "processing" | "ready" | "failed";
    export const Status = {
        Waiting: "waiting",
        Processing: "processing",
        Ready: "ready",
        Failed: "failed",
    } as const;
}
