/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface MediaSource {
    id: string;
    object: MediaSource.Object_;
    kind: MediaSource.Kind;
    type: string;
    codec?: string;
    container?: string;
    width?: number;
    height?: number;
    orientation?: MediaSource.Orientation;
    rotation?: number;
    transparency?: boolean;
    frames?: number;
    duration?: number;
    fps?: number;
    filesize: number;
    bitrate?: number;
    ref?: string;
    folder?: string;
    filename?: string;
    url: string;
    metadata?: Record<string, unknown>;
    original?: boolean;
    created: string;
    updated: string;
    status: MediaSource.Status;
}

export namespace MediaSource {
    export type Object_ = "source" | "track" | "intelligence";
    export const Object_ = {
        Source: "source",
        Track: "track",
        Intelligence: "intelligence",
    } as const;
    export type Kind = "video" | "image" | "audio";
    export const Kind = {
        Video: "video",
        Image: "image",
        Audio: "audio",
    } as const;
    export type Orientation = "landscape" | "portrait" | "square";
    export const Orientation = {
        Landscape: "landscape",
        Portrait: "portrait",
        Square: "square",
    } as const;
    export type Status = "waiting" | "processing" | "ready" | "failed";
    export const Status = {
        Waiting: "waiting",
        Processing: "processing",
        Ready: "ready",
        Failed: "failed",
    } as const;
}
