/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type Status = "pending" | "waiting" | "processing" | "ready" | "completed" | "failed" | "error" | "cancelled";
export const Status = {
    Pending: "pending",
    Waiting: "waiting",
    Processing: "processing",
    Ready: "ready",
    Completed: "completed",
    Failed: "failed",
    Error: "error",
    Cancelled: "cancelled",
} as const;
