/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         url: "https://ittyb.it/sample.mp4",
 *         folder: "ittybit/samples",
 *         filename: "video.mp4",
 *         metadata: {
 *             "customKey": "your custom value"
 *         }
 *     }
 */
export interface FilesCreateRequest {
    url: string;
    media_id?: string;
    folder?: string;
    filename?: string;
    ref?: string;
    metadata?: Record<string, unknown>;
}
